version: '3.9'
services:
  # service used for development
  dev:
    # NOTE: all paths below are relative to the primary docker-compose.yml file,
    # e.g. the first in the devcontainer.json "dockerComposeFile" array.

    build:
      context: .
      dockerfile: Dockerfile.dev

    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - .:/code:cached

      # Uncomment the next line to use Docker from inside the container. See https://aka.ms/vscode-remote/samples/docker-from-docker-compose for details.
      - /var/run/docker.sock:/var/run/docker.sock 

    # Uncomment the next four lines if you will use a ptrace-based debugger like C++, Go, and Rust.
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

    # Used to allow ROS2's underlying DDS to communicate across containers
    ipc: service:donor
    pid: service:donor

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
 
